# Generated by Django 2.2.3 on 2019-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='trailingRevisionNumber',
            field=models.IntegerField(default=-1),
        ),
    ]
