# Generated by Django 2.2.2 on 2019-09-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_query_trailingrevisionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='auto_update_trailing_revision',
            field=models.BooleanField(default=True),
        ),
    ]
