---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        tier: {{ quote .Values.service.tier }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "name" . }}
        image: {{ .Values.image.repositoryBaseURL }}/{{ template "name" . }}:{{ template "appversion" . }}
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: {{ .Values.server.context.path }}/health
            port: sb-port
          initialDelaySeconds: 15
        env:
        - name: DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.database.host }}-jdbc-urls
              key: {{ .Values.database.name }}
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.userSecret.name }}
              key: {{ .Values.database.userSecret.key }}
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.passwordSecret.name }}
              key: {{ .Values.database.passwordSecret.key }}
        ports:
        - containerPort: 8080
          name: sb-port
        resources:
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
      - name: myregistrykey
