apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    tier: {{ quote .Values.service.tier }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - port: 80
      targetPort: sb-port
      protocol: TCP
  selector:
    app: {{ template "name" . }}
    tier: {{ quote .Values.service.tier }}
